Node.create(name: 'Back of the room')
Node.create(name: 'Front of the room')
Node.create(name: 'Elevators')
Node.create(name: 'Service elevator')
Node.create(name: 'Kitchen')
Node.create(name: 'Phone booth')
